name: gruby
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  flutter_barcode_scanner: ^2.0.0
  intl: ^0.18.1
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  flutter_typeahead: ^5.2.0
  path: ^1.9.1

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true
